import { asEntities } from '../extendable/entity';

export const ENEMIES = asEntities({
  dragon: {
    attacks: [],
    icon: '🐉',
    id: 'dragon',
    name: 'Dragon',
    stats: {
      attack: 5,
      crit_chance: 5,
      crit_dmg: 50,
      defense: 5,
      elemental_dmg_bonuses: {
        fire: 0,
        ice: 0,
        lightning: 0,
        physical: 0,
        water: 0,
        wind: 0,
      },
      energy: 10,
      energy_regen: 1,
      healing_bonus: 0,
      hp: 50,
      max_energy: 10,
      max_hp: 50,
      reaction_bonus: 0,
      resistances: {
        fire: 0,
        ice: 0,
        lightning: 0,
        physical: 0,
        water: 0,
        wind: 0,
      },
    },
  },
  goblin: {
    attacks: [],
    icon: '👺',
    id: 'goblin',
    name: 'Goblin',
    stats: {
      attack: 10,
      crit_chance: 5,
      crit_dmg: 5,
      defense: 10,
      elemental_dmg_bonuses: {
        fire: 0,
        ice: 0,
        lightning: 0,
        physical: 0,
        water: 0,
        wind: 0,
      },
      energy: 10,
      energy_regen: 1,
      healing_bonus: 0,
      hp: 500,
      max_energy: 10,
      max_hp: 500,
      reaction_bonus: 0,
      resistances: {
        fire: 0,
        ice: 0,
        lightning: 0,
        physical: 0,
        water: 0,
        wind: 0,
      },
    },
  },
  orc: {
    attacks: [],
    icon: '👹',
    id: 'orc',
    name: 'Orc',
    stats: {
      attack: 5,
      crit_chance: 5,
      crit_dmg: 50,
      defense: 5,
      elemental_dmg_bonuses: {
        fire: 0,
        ice: 0,
        lightning: 0,
        physical: 0,
        water: 0,
        wind: 0,
      },
      energy: 10,
      energy_regen: 1,
      healing_bonus: 0,
      hp: 50,
      max_energy: 10,
      max_hp: 50,
      reaction_bonus: 0,
      resistances: {
        fire: 0,
        ice: 0,
        lightning: 0,
        physical: 0,
        water: 0,
        wind: 0,
      },
    },
  },
  troll: {
    attacks: [],
    icon: '👿',
    id: 'troll',
    name: 'Troll',
    stats: {
      attack: 50,
      crit_chance: 50,
      crit_dmg: 50,
      defense: 100,
      elemental_dmg_bonuses: {
        fire: 0,
        ice: 0,
        lightning: 0,
        physical: 0,
        water: 0,
        wind: 0,
      },
      energy: 10,
      energy_regen: 1,
      healing_bonus: 0,
      hp: 50,
      max_energy: 10,
      max_hp: 50,
      reaction_bonus: 0,
      resistances: {
        fire: 0,
        ice: 0,
        lightning: 0,
        physical: 0,
        water: 0,
        wind: 0,
      },
    },
  },
});
