import { asEntities } from '../extendable/entity';

export const ENEMIES = asEntities({
  dragon: {
    icon: '🐉',
    id: 'dragon',
    name: 'Dragon',
    stats: {
      attack: 5,
      crit_chance: 5,
      crit_dmg: 150,
      defense: 5,
      elemental_dmg_bonus: 0,
      energy: 10,
      energy_regen: 1,
      healing_bonus: 0,
      hp: 50,
      max_energy: 10,
      max_hp: 50,
      physical_dmg_bonus: 0,
      reaction_bonus: 0,
    },
  },
  goblin: {
    icon: '👺',
    id: 'goblin',
    name: 'Goblin',
    stats: {
      attack: 1,
      crit_chance: 5,
      crit_dmg: 150,
      defense: 1,
      elemental_dmg_bonus: 0,
      energy: 10,
      energy_regen: 1,
      healing_bonus: 0,
      hp: 5,
      max_energy: 10,
      max_hp: 5,
      physical_dmg_bonus: 0,
      reaction_bonus: 0,
    },
  },
  orc: {
    icon: '👹',
    id: 'orc',
    name: 'Orc',
    stats: {
      attack: 5,
      crit_chance: 5,
      crit_dmg: 150,
      defense: 5,
      elemental_dmg_bonus: 0,
      energy: 10,
      energy_regen: 1,
      healing_bonus: 0,
      hp: 50,
      max_energy: 10,
      max_hp: 50,
      physical_dmg_bonus: 0,
      reaction_bonus: 0,
    },
  },
  troll: {
    icon: '👿',
    id: 'troll',
    name: 'Troll',
    stats: {
      attack: 5,
      crit_chance: 5,
      crit_dmg: 150,
      defense: 5,
      elemental_dmg_bonus: 0,
      energy: 10,
      energy_regen: 1,
      healing_bonus: 0,
      hp: 50,
      max_energy: 10,
      max_hp: 50,
      physical_dmg_bonus: 0,
      reaction_bonus: 0,
    },
  },
});
