import { asTerrainCells } from '../extendable/map';

export const TERRAIN_CELLS = asTerrainCells({
  Beach: {
    className: 'Beach',
    dangerLevel: 2,
    description: 'Beach',
    icon: '🏖️',
    id: 'Beach',
    name: 'Beach',
  },
  Field: {
    className: 'Field',
    dangerLevel: 1,
    description: '',
    icon: '🌿',
    id: 'Field',
    name: 'Field',
  },
  Forest: {
    className: 'Forest',
    dangerLevel: 3,
    description: '',
    icon: '🌳',
    id: 'Forest',
    name: 'Forest',
  },
  Meadow: {
    className: 'Meadow',
    dangerLevel: 2,
    description: '',
    icon: '🌾',
    id: 'Meadow',
    name: 'Meadow',
  },
  Mountain: {
    className: 'Mountain',
    dangerLevel: 4,
    description: '',
    icon: '⛰️',
    id: 'Mountain',
    name: 'Mountain',
  },
  Ocean: {
    className: 'Ocean',
    dangerLevel: 3,
    description: '',
    icon: '🌊',
    id: 'Ocean',
    name: 'Ocean',
  },
  Volcano: {
    className: 'Volcano',
    dangerLevel: 5,
    description: '',
    icon: '🌋',
    id: 'Volcano',
    name: 'Volcano',
  },
});
