import { asGears } from '../../extendable/gear';

export const MELEE = asGears({
  BoneSword: {
    category: 'gear',
    cost: 1,
    description: '',
    h: 3,
    icon: '🗡️',
    id: 'BoneSword',
    name: 'Bone Sword',
    rarity: 'common',
    subicon: '🦴',
    type: 'melee',
    w: 1,
    weight: 1000,
  },
  FireSword: {
    category: 'gear',
    cost: 1,
    description: 'Simple wooden sword',
    h: 4,
    icon: '🗡️',
    id: 'FireSword',
    name: 'Fire Sword',
    rarity: 'rare',
    subicon: '🔥',
    type: 'melee',
    w: 1,
    weight: 1000,
  },
  IceSword: {
    category: 'gear',
    cost: 1,
    description: 'Simple wooden sword',
    h: 4,
    icon: '🗡️',
    id: 'IceSword',
    name: 'Ice Sword',
    rarity: 'rare',
    subicon: '🧊',
    type: 'melee',
    w: 1,
    weight: 1000,
  },
  SwordOfTime: {
    category: 'gear',
    cost: 1,
    description: '',
    h: 4,
    icon: '🗡️',
    id: 'SwordOfTime',
    name: 'The Sword Of Time',
    rarity: 'legendary',
    subicon: '⏳',
    type: 'melee',
    w: 1,
    weight: 1000,
  },
  WoodenStaff: {
    category: 'gear',
    cost: 1,
    description: '',
    h: 3,
    icon: '⚚',
    id: 'WoodenStaff',
    name: 'Wooden Staff',
    rarity: 'common',
    subicon: '🪵',
    type: 'melee',
    w: 1,
    weight: 1000,
  },
  WoodenSword: {
    category: 'gear',
    cost: 1,
    description: 'Simple wooden sword',
    h: 3,
    icon: '🗡️',
    id: 'WoodenSword',
    name: 'Wooden Sword',
    rarity: 'common',
    subicon: '🪵',
    type: 'melee',
    w: 1,
    weight: 1000,
  },
});
