import { asGears } from '../../extendable/gear';

export const RANGE = asGears({
  BoneBow: {
    category: 'gear',
    cost: 2,
    description: '',
    h: 3,
    icon: '🏹',
    id: 'BoneBow',
    name: 'Bone Bow',
    rarity: 'common',
    stats: [],
    subicon: '🦴',
    type: 'range',
    w: 2,
    weight: 1000,
  },
  Bow: {
    category: 'gear',
    cost: 1,
    description: 'Simple wooden sword',
    h: 3,
    icon: '🏹',
    id: 'Bow',
    name: 'Bow',
    rarity: 'common',
    stats: [],
    type: 'range',
    w: 2,
    weight: 1000,
  },
  BowOfTime: {
    category: 'gear',
    cost: 1,
    description: 'Simple wooden sword',
    h: 3,
    icon: '🏹',
    id: 'BowOfTime',
    name: 'The Bow Of Time',
    rarity: 'legendary',
    stats: [],
    subicon: '⏳',
    type: 'range',
    w: 2,
    weight: 1000,
  },
  FireBow: {
    category: 'gear',
    cost: 1,
    description: 'Simple wooden sword',
    h: 4,
    icon: '🏹',
    id: 'FireBow',
    name: 'Fire Bow',
    rarity: 'rare',
    stats: [],
    subicon: '🔥',
    type: 'range',
    w: 1,
    weight: 1000,
  },
  IceBow: {
    category: 'gear',
    cost: 1,
    description: 'Simple wooden sword',
    h: 4,
    icon: '🏹',
    id: 'IceBow',
    name: 'Ice Bow',
    rarity: 'rare',
    stats: [],
    subicon: '🧊',
    type: 'range',
    w: 1,
    weight: 1000,
  },
});
